### ISSUE TITLE
Play Store FC

### ISSUE THREAD

**Issue by Micks29** [GermainZ/PlayPermissionsExposed#10]
Already report on XDA.
<a href="http://www.hostingpics.net/viewer.php?id=852837Screenshot20150410092024.png"><img src="http://img11.hostingpics.net/thumbs/mini_852837Screenshot20150410092024.png" alt="Upload images" /></a>

**Comment by GermainZ** [comment]
Someone on XDA suggested a fix, but no one replied to them so I assumed 
it's not
an issue. Did you try that?

**Comment by Micks29** [comment]
No because no problem before today, it's happen with just an app (CM Security) in my case.

**Comment by GermainZ** [comment]
Can you post the logcat (not an image, but text if possible) filtered for
AndroidRuntime? Please never filter by the app's name, that only cuts out 
useful
information.

**Comment by Micks29** [comment]
Well I can't reproduce the issue sorry.
